### ISSUE TITLE
Addon Manager 

### ISSUE THREAD

**Issue by bugeaud** [rkrenzler/ose-piping-workbench#3]
If possible, it would be nice to get the OSE Piping WB inside the addon manager.
https://wiki.freecadweb.org/Std_AddonMgr

**Comment by rkrenzler** [comment]
OK. I will try to add the Workbench to the Addon-Manager in July. Provided the FreeCAD community is not not against it.

**Comment by rkrenzler** [comment]
I started to prepare my workbench for the Addon Manager. It is a multi-step process. See https://github.com/FreeCAD/FreeCAD-addons/.  It will take some time.

**Comment by rkrenzler** [comment]
Done. The Addon Manger can now install OSE-Piping workbench.
