### ISSUE TITLE
Add snap fit

### ISSUE THREAD

**Issue by bugeaud** [rkrenzler/ose-piping-workbench#6]
Add a command that snap fit two piping item if the current selection has two plane part selected (like the colar of an elbow and one side of a pipe).

This would involve computing the rotation & translation and then performing it thru the suited scripting.

It would make building of complex piping system easier.

AFAIK, at this time you can do this by hand but the process is tedious and time consuming.
(assuming I did not missed a magic feature from FreeCAD that does this already)

**Comment by rkrenzler** [comment]
I added some experimental "Move Around" and "Move To" commands to the workbench.
Use "Move Around" to move a single part.
Use "Move To" to connect one part to another.
