### ISSUE TITLE
Add parametric data for piping

### ISSUE THREAD

**Issue by bugeaud** [rkrenzler/ose-piping-workbench#7]
Let's have the caracteristics of the piping items as data in the property editor of the object.

Changing those data would simply update the piping item live.

As an example, caracteristics of a pipe are at least 
- Length
- Diameter (DN100mm [default])
- Fitting type on side 1 (Male [default] or Female)
- Fitting type on side 2 (Male [default] or Female)

For elbow, I expect bend angle caracteristics added and Length removed. Etc

**Comment by rkrenzler** [comment]
You can already change  some parameters if you create flamingo parts.
This includes, for example, the length, diameter, and wall thickness of a pipe.

**Comment by rkrenzler** [comment]
You can change the bend angle of flamingo-elbow.

**Comment by rkrenzler** [comment]
The F & M types type of fittings will require too much development -- I will focus on other issues first.

**Comment by rkrenzler** [comment]
Live change of the length and the diameter is already implemented for Dodo/Flamingo pipes.

F&M types is a too complex for a fast impementation.
