### ISSUE TITLE
Add snap rotation

### ISSUE THREAD

**Issue by bugeaud** [rkrenzler/ose-piping-workbench#8]
If snap fit #6 is implemented, it would be nice to get a rotation feature that enable a selected item to be rotated atound its axis of liberty.

Rotating an item axis will keep other snapped item attached.

Pipe : 1 degree of liberty (rotation us is useless ?)
Elbow : 2 degree of liberty (1 on each end)

**Comment by rkrenzler** [comment]
I did some experiments with rotations. When I
